### ISSUE TITLE
satsujin has no swimming animation when the underwater knife is inserted into the scabbard

### ISSUE THREAD

**Issue by fzrdwa123456** [Reascer/WeaponsOfMinecraft-1.18.2#10]
https://github.com/Reascer/WeaponsOfMinecraft-1.18.2/assets/130232431/a9fdc42c-b442-4bff-aefe-c4e3dab47845

**Comment by fzrdwa123456** [comment]
Minecraft 1.18.2
Forge 40.2.10
Epic Fight 18.5.12 release
Weapons Of Miracles 1.7.11

**Comment by Reascer** [comment]
i'll look up at that

**Comment by fzrdwa123456** [comment]
> i'll look up at that

So you're willing to fix this, right?

**Comment by fzrdwa123456** [comment]
> i'll look up at that

Thank you for the latest version you have fixed
