### ISSUE TITLE
1.20.1 | The mod is not loading, i have both epic fight and WOM in their latest version

### ISSUE THREAD

**Issue by DARKLOL680** [Reascer/WeaponsOfMinecraft-1.18.2#100]
![2024-01-19_23 08 58](https://github.com/Reascer/WeaponsOfMinecraft-1.18.2/assets/121734819/53faa153-ef15-4f14-a996-19f71a7e94b2)

**Comment by DARKLOL680** [comment]
[latest.log](https://github.com/Reascer/WeaponsOfMinecraft-1.18.2/files/14002565/latest.log)

**Comment by NekoLeila** [comment]
Am having the same problem, just updated to the latest version and now it crashes every time I try to start the game. Even going back to older versions doesn't fix it.

**Comment by Reascer** [comment]
downgrade epicfight

**Comment by DARKLOL680** [comment]
it solved the problem, thanks !
