### ISSUE TITLE
Skills say unusable

### ISSUE THREAD

**Issue by ParaLumic** [Reascer/WeaponsOfMinecraft-1.18.2#109]
![024918b3-5b4f-4fb6-8514-df069a260176](https://github.com/Reascer/WeaponsOfMinecraft-1.18.2/assets/147652756/dae487ea-2695-4558-bd8f-8a4441910627)

1.20.1

I have 6 skills I can't unlock being vengeful parry, Bull charge, shadow step, counter attack, perfect bulwark, and dodge master

The skill I currently have are - for dodge are roll, step, and precise roll
For guard I have guard, impact guard, and parrying

When I hover over a skill that says unusable it doesn't tell me what skill I need to be able to learn it. apparently I already have the skill that I need to unlock some some of them. 

I just discovered this a little bit later, a skill I already have says unusable while others that I also already have don't so I'm even more confused but know it has to be some kind of bug

**Comment by KDFireHero** [comment]
some skills have prerequisites that need to be active at the time you learning the new skill, I don't remember exactly but it something like have Step equipped, then try to learn shadow step, it might be a different combination but I think I got the idea across
