### ISSUE TITLE
[Suggestion]Add "Stronger mob now scale properly!" to the config file. Turn on or off and adjust functions

### ISSUE THREAD

**Issue by fzrdwa123456** [Reascer/WeaponsOfMinecraft-1.18.2#13]
"Finaly find a way to fix Meditation messing with Satsujin sheathing and Enderblasters reload 
Stronger mob now scale properly ! Exemple for a zombie hp :
at 0 < 1000 block radius = 20 hp ( base hp )
at 1000 < 2000 block radius = 30 hp  ( base hp * 1.5^1 )
at 2000 < 3000 block radius = 45 hp  ( base hp * 1.5^2 )
at 3000 < 4000 block radius = 67.5 hp  ( base hp * 1.5^3 )
This goes on and on..."

Can the feature you added in 1.7.14 be turned on or selected and adjusted by the player? This can cause the game's numerical balance to be broken
After all similar mods have this feature like "Auto Leveling"

**Comment by fzrdwa123456** [comment]
Can you add the switch for this function in config?

**Comment by fzrdwa123456** [comment]
It would be nice if the player could make their own adjustments in config

**Comment by Reascer** [comment]
it's deactivated by default and there is a gamerule to activate or deactivate it

**Comment by fzrdwa123456** [comment]
> it's deactivated by default and there is a gamerule to activate or deactivate it

Thank you
