### ISSUE TITLE
Difficulties to hit mobs

### ISSUE THREAD

**Issue by KamiSami** [Reascer/WeaponsOfMinecraft-1.18.2#14]
Hey, i put this issue earlier in discord bugs section but am not sure if you keep track of it but here instead, so thought to make this issue here too. Basically it is sometimes really hard to hit mobs that are about side of player such as zombies and skeletons etc, at least when using antitheus and satsujin, i don't recall this being problem when i had the patreon 1.6 version before... Gonna attach a gif here so you see what i mean. Also question, is it normal that you are unable to jump after certain special attacks? As it happens to me.
![bug](https://github.com/Reascer/WeaponsOfMinecraft-1.18.2/assets/24697798/3bde3ac5-1b5b-4035-8db5-bbd928fbad4f)

**Comment by Reascer** [comment]
You are playing with stiffwombo attack + Camera lock T-T (crying blood)
