### ISSUE TITLE
UI rendering error

### ISSUE THREAD

**Issue by fzrdwa123456** [Reascer/WeaponsOfMinecraft-1.18.2#20]
https://github.com/Reascer/WeaponsOfMinecraft-1.18.2/assets/130232431/e0fee6e9-b953-408f-a0d3-efc912e41796

You can see that your mod is having UI issues in version 1.20.1 and has broken some displays such as the potion effect icon in the upper right corner.
And the weapon skills in the lower right corner also flicker.
Minecraft 1.20.1
Fogre 47.2.1
Epic fight 20.5.15
Weapons Of Miracles-20.1.7.19

**Comment by fzrdwa123456** [comment]
The same problem may exist in 1.19.2

**Comment by Reascer** [comment]
The flicker is intended 
I'll try to fix missing texture assap

**Comment by fzrdwa123456** [comment]
> The flicker is intended I'll try to fix missing texture assap

So flicker is not a bug but a unique feature of the "Torment" weapon ?

**Comment by Reascer** [comment]
Yes
