### ISSUE TITLE
Weapon categories don't work properly on datapacks

### ISSUE THREAD

**Issue by NEFFLEAFF** [Reascer/WeaponsOfMinecraft-1.18.2#21]
For example ruine acts like a sword in mob patch, satsujin is a uchigatana, staff is a spear, etc.
No matter what I do these keep ignoring their true category.

Speaking of datapacks, why does trying to use any antitheus animation for entities crash the game?

**Comment by Reascer** [comment]
Wom wasn't really meant for datapack but I'm working on making this work I just have billions of stuff to fix ....
