### ISSUE TITLE
Disconnect from dedicated server with latest EF

### ISSUE THREAD

**Issue by ArcaneSan** [Reascer/WeaponsOfMinecraft-1.18.2#23]
EF 1.20.1 version 20.5.15. 
Tested with just EF and WOM. 

~When entering combat mode and attempting to attack (not just wom weapons) the player will be disconnected from the server. This will appear after connection lost. ~

![image](https://github.com/Reascer/WeaponsOfMinecraft-1.18.2/assets/78715746/fa1e1b56-a070-40ee-be9e-d5e7674f9692)

Server and client do not crash from this issue. Server logs just repeat the same thing. It works fine on single player, just not a dedicated server

EDIT refreshing configs fixed the combat issue, but when using [Perfect Bulwark] The issue happens still happens on a server. Another person also had the issue with [Counter attack] but I didn't have the issue

**Comment by Mnibr** [comment]
This issue occurred when I was using the latest version of rubidium. Please try replacing rubidium with Embeddium

**Comment by ArcaneSan** [comment]
> This issue occurred when I was using the latest version of rubidium. Please try replacing rubidium with Embeddium

I'm still experiencing these types of issue with Embeddium on my modpack, but the times I tested it were with only EF and WOM, nothing else

**Comment by ArcaneSan** [comment]
Updated with latest EF and WOM...

With just those two mods Perfect bulkwark causes a disconnect with the server still....

With embeddium is seems that occasionally Counter attack causes disconects
