### ISSUE TITLE
Texture Rendering Bug

### ISSUE THREAD

**Issue by Briknex** [Reascer/WeaponsOfMinecraft-1.18.2#25]
Agony, Herrscher, and Gesetz' textures are bugged. I'm not using any texture packs.
![Agony Rendering Bug](https://github.com/Reascer/WeaponsOfMinecraft-1.18.2/assets/125288735/183c2712-5354-420d-a024-e1d2fd9a6fea)
![Gesetz and Herrscher Rendering Bug](https://github.com/Reascer/WeaponsOfMinecraft-1.18.2/assets/125288735/2fc5603b-0b1e-4570-af1d-f72e55d8a4fa)

**Comment by Reascer** [comment]
update WoM
