### ISSUE TITLE
ender blast doesn't recharge

### ISSUE THREAD

**Issue by Princlei152** [Reascer/WeaponsOfMinecraft-1.18.2#28]
WeaponsOfMiracles-18.1.7.26.jar
over time the ender blast stops recharging.

**Comment by Kiro-D-P1R4T3** [comment]
same here.
ender blasters does not recharge on a dedicated server( 1.18.2/ forge 40.2.10 ), however they do on single player.
I made  a fresh server with just the 2 mods (EF and WOM) so Im sure its not a compatibility issue with other mods.

**Comment by Reascer** [comment]
do you have meditation ?

**Comment by Kiro-D-P1R4T3** [comment]
me. nope

**Comment by Princlei152** [comment]
i have meditation

**Comment by Reascer** [comment]
huh, the animation plays but it's doesn't actully add the ammo right ?

**Comment by Princlei152** [comment]
No animation and no reload

**Comment by Princlei152** [comment]
To get back to normal I'm throwing my weapons on the ground and picking them back up every time it happens

**Comment by Reascer** [comment]
Well you need to wait it's a bug from epicfight i can fix it by making the bullet add up befor the animation but it will be ugly af

**Comment by Princlei152** [comment]
@Don't worry friend, I'll try other versions of Forge to see if it works, I was in this because of Mutant Beast, it requires 40.2.7 but I jumped straight to 40.2.10

**Comment by Kiro-D-P1R4T3** [comment]
> huh, the animation plays but it's doesn't actully add the ammo right ?

thats my issue on my dedicated server

**Comment by kevinWithoutSuace** [comment]
same thing here, works in singleplayer but not in a server, looking at the comments I am sure it is not mod incompatibility or the wrong version. I saw a new update that dropped earlier today that supposedly fixed the ender blaster but the bug still remained in servers.

**Comment by Reascer** [comment]
don't worry i'm searching for a way to fix it
