### ISSUE TITLE
Bro, 20.1.28 still has a bug where WOM's weapons cannot be hit in combat mode

### ISSUE THREAD

**Issue by Mnibr** [Reascer/WeaponsOfMinecraft-1.18.2#36]
https://github.com/Reascer/WeaponsOfMinecraft-1.18.2/assets/147657979/920bde6b-394e-4509-a3f2-e7dd51f8a7eb

**Comment by Mnibr** [comment]
The video only shows one type of weapon, but all weapons are actually unable to hit, in combat mode

**Comment by Mnibr** [comment]
The video only shows one type of weapon, but in combat mode, all WOM's weapons are actually unable to hit

**Comment by Mnibr** [comment]
Finally, you can see that I switched the Trident to kill this Husk, and Jade also displayed Husk's health. This attack will definitely hit, but in reality, it did not

**Comment by Reascer** [comment]
Are you playing in server ?

**Comment by Mnibr** [comment]
> Are you playing in server ?

No, this problem was first found in the server, but now it has been tested, and the single-player mode also has this bug. I'm not sure if it is the reason why I replaced the low-version module with the high-version module. At present, both the single-player mode and the server have this problem, but I have only tested it in save with the old version of wom, but obviously this is ridiculous, so please test it.

**Comment by Mnibr** [comment]
> Are you playing in server ?

This problem appears in 47.2.1/47.2.0 of the client forge and 47.1.44 of the server forge (the core of the highest version of the server), And this problem of not hitting the target appears above 20.1.7.26 of wom, and now 20.1.7.28, and there is no such problem in 20.1.7.19 to 20.1.7.22.

**Comment by Reascer** [comment]
i tested it again and again every thing is fine on my side

**Comment by Mnibr** [comment]
> 我一遍又一遍地测试它，我这边的一切都很好......无法重现错误或找到它可能来自哪里。

BRO, after my testing, WOM's weapon was unable to hit creatures whose original biological model animation was disabled by Datapack. In the video, this Husk was disabled by me, which means that WOM's weapon cannot hit them in biological combat mode with the following code disabled animation

**Comment by Mnibr** [comment]
{
    "disabled": true
}

**Comment by Mnibr** [comment]
Creatures that disable animation using this data packet code cannot be hit by WOM's weapon

**Comment by Mnibr** [comment]
Normal attacks that cannot be hit with a single left click here, both skill and right click attacks can hit

**Comment by Mnibr** [comment]
I'm sorry, I didn't know that only data packets would trigger, and it wasn't until you just sent me this message that I realized it
