### ISSUE TITLE
Can not join sever with wom weapons hold in hands

### ISSUE THREAD

**Issue by linxcy** [Reascer/WeaponsOfMinecraft-1.18.2#37]
![image](https://github.com/Reascer/WeaponsOfMinecraft-1.18.2/assets/67699852/a7badedc-4235-42a1-ba75-834ca93f8c8d)

After disconnect from the sever， it shows this message.

**Comment by Reascer** [comment]
send me full crashlog

**Comment by linxcy** [comment]
Game not crash , just sending this message again and again when i join the sever

**Comment by linxcy** [comment]
and if stiffComboAttacks is false, the game crashed when i using the Antitheus.
After i using the skill and try to attack while moving，the game crash.
[crash-2023-10-30_19.58.09-client.txt](https://github.com/Reascer/WeaponsOfMinecraft-1.18.2/files/13215102/crash-2023-10-30_19.58.09-client.txt)
Here is the crash report.

**Comment by Reascer** [comment]
cheach if you have ressouces pack  or datapack that mess with efm or WoM

**Comment by linxcy** [comment]
i made a datapack that use some wom action on mod weapons.
is that the reasons？

**Comment by Reascer** [comment]
remove them and let's see

**Comment by linxcy** [comment]
it seems that if i use the weapon skills, the text appear

**Comment by linxcy** [comment]
The current situation is that it does not happen every time the game is started, and the probability of this problem occurring is random

**Comment by Reascer** [comment]
don't use 1.19.2 in server for now
