### ISSUE TITLE
WoM weapons dont detect hits on entities that are disabled thru datapacks

### ISSUE THREAD

**Issue by zGh0stY** [Reascer/WeaponsOfMinecraft-1.18.2#38]
Disable any entity with a Datapack and WoM weapons wont be able to hit them.

Example Datapack:
[Example.zip](https://github.com/Reascer/WeaponsOfMinecraft-1.18.2/files/13230105/Example.zip)

**Comment by Mnibr** [comment]
This problem has been raised by me and solved by the author. Please wait for the next update.
