### ISSUE TITLE
Right Click for Tormented Mind Not Working after Using Inate Skill

### ISSUE THREAD

**Issue by Nether-Beast72** [Reascer/WeaponsOfMinecraft-1.18.2#4]
Video: https://streamable.com/0t9fgg

Right click works without the inate skill being active, but it doesn't work/play animations when inate skill IS active. I've updated my EFM and WoM to the latest versions on Curseforge, so Idk what could be causing the problem. I'm gonna try reinstalling both mods again to see if I just made a mistake. (I'll let you know if that was my issue).

**Comment by Reascer** [comment]
It's normal you not suppose to charge attack in true berserk
