### ISSUE TITLE
1.19.2 server disconnect when using teleportation

### ISSUE THREAD

**Issue by Amory42** [Reascer/WeaponsOfMinecraft-1.18.2#41]
Whenever I use any of the skills or weapons that involve Teleportation (i.e. Ender Obscuris, Moonlight, Satsujin, etc), then the server disconnects me and gives me this error code

"java.lang.IndexOutOfBoundsException: readerIndex(13) + length(4) exceeds writerIndex(14): PooledUnsafeDirectByteBuf(ridx: 13, widx: 14, cap: 14)"

**Comment by Reascer** [comment]
send me full crashlog i'll see what i can do
