### ISSUE TITLE
Mod license is ambiguous

### ISSUE THREAD

**Issue by Kasualix** [Reascer/WeaponsOfMinecraft-1.18.2#43]
[ARR in mods.toml](https://github.com/Reascer/WeaponsOfMinecraft-1.18.2/blob/c83b44fab9ac96618e64e4a4aa2265e58fee6433/src/main/resources/META-INF/mods.toml#L12)
[Forge MDK rubbish LGPL-v2.1](https://github.com/Reascer/WeaponsOfMinecraft-1.18.2/blob/1.19.x/LICENSE.txt)
[GPLv3 on CurseForge](https://www.curseforge.com/minecraft/mc-mods/weapons-of-miracles-epicfight#license) (btw I don't think GPLv3 is compatible with Minecraft but I may be wrong)

**Comment by Reascer** [comment]
thanks i'll fix this
