### ISSUE TITLE
Bro!!!! Why not hit the problem has not been solved yet!!! I have been waiting for your update for a long time, but the latest version still hasn't been resolved (although you indicated in the issues that it has been resolved)

### ISSUE THREAD

**Issue by Mnibr** [Reascer/WeaponsOfMinecraft-1.18.2#44]
Did you forget?(I didn't mean to urge you, it's just that this problem has been around for a long time.)

**Comment by Mnibr** [comment]
Did you forget?

**Comment by Mnibr** [comment]
I have been troubled by this problem for almost half a month

**Comment by Reascer** [comment]
what are talking about it's a datapack thing just remove datapack i cannot change epicfight datapack feature

**Comment by Mnibr** [comment]
> what are talking about it's a datapack thing just remove datapack i cannot change epicfight datapack feature

This is not a datapack problem, because this problem appeared after 20.1.7.22 of wom, which means that this problem is caused by reascer's change of wom.

**Comment by Mnibr** [comment]
If it is really the function of datapack, why didn't the previous wom cause this problem?

**Comment by Mnibr** [comment]
And what is forbidden is the action of the entity, not the action of the weapon. Why can it lead to the inability to hit the entity?
