### ISSUE TITLE
1.20.1 Server. Kicks when doing the innate on agony and sometime kicks with other weapons and torment kicks you over and over

### ISSUE THREAD

**Issue by TheCatLord0** [Reascer/WeaponsOfMinecraft-1.18.2#46]
I sadly don't have the logs but the title says it all

**Comment by Reascer** [comment]
what version of WoM ?

**Comment by Reascer** [comment]
and well i'll be honest your tittle doesn't make sense if you could record maybe ?

**Comment by TheCatLord0** [comment]
Will record it soon. Already deleted WoM from my server so don’t remember what version but I can get a fresh instance of the pack to see

**Comment by TheCatLord0** [comment]
it was on last version rip lol
Ima see if it works on the newest soon

**Comment by ArcaneSan** [comment]
Adding onto this, might be related, but upgrading WOM from 20.1.7.29 to latest will fix the issue on the server, but restarting the server will somehow bring back the issues unless you once again downgrade and then upgrade. Haven't tested it in a clean environment yet, but thats what I've done in a modpack to fix it. 

Not sure if the information helps in any way, but I was able to join with different versions of WOM as well if it matters

**Comment by Reascer** [comment]
you don't need to downgrade or upgrade
just restart server until all is fine sorry

**Comment by Cubulous** [comment]
I am having this issue when I add Torment to my inventory. I have restarted the server several times, and also the client, and I'm still getting this:

![tormentissue](https://github.com/Reascer/WeaponsOfMinecraft-1.18.2/assets/150428966/c585ca6b-a096-464a-aa35-3b512e559add)

I then have to go in and remove Torment from the player dat file.

Thanks for all your hard work and for this amazing mod!
