### ISSUE TITLE
Some crash issues

### ISSUE THREAD

**Issue by Mnibr** [Reascer/WeaponsOfMinecraft-1.18.2#47]
https://drive.google.com/file/d/1IFJuBpMkRfYEg7Kvnr0r_HSnHBKq39V1/view?usp=drive_link
The above are the client logs during the crash, which occurred between 1:15 and 1:25. However, to prevent any omissions, I uploaded all logs from 1:00 to 2:00
![image](https://github.com/Reascer/WeaponsOfMinecraft-1.18.2/assets/147657979/ab54b900-447f-48ee-a7b4-bcfc01481940)
According to the testing results of our community, the reasons for the server crash include: Antithus being placed on the item list and Satsujin being instantly killed
And these two particle effects: 'They will cause the item to attack and collapse'
![image](https://github.com/Reascer/WeaponsOfMinecraft-1.18.2/assets/147657979/463add02-52a5-4ef7-ad6b-a5edc88558ae)
![image](https://github.com/Reascer/WeaponsOfMinecraft-1.18.2/assets/147657979/c59c655b-4c4a-4095-b0fb-0bee7d39da97)

**Comment by Mnibr** [comment]
The server has no logs, which is a client crash. WOM version 20.1.7.31 and EFM version 20.5.16. After a period of testing, the EFM version 20.5.15 and WOM with crash issues will not crash due to attacks, but all active skills will be disabled. Using meditation will crash

**Comment by Mnibr** [comment]
But this problem occurs only on the server

**Comment by Mnibr** [comment]
But this issue only occurs on the server and only occurs when WOM and EFM are specific versions

**Comment by Mnibr** [comment]
This issue occurs in any 1.20.1 forge version

**Comment by Mnibr** [comment]
A friend who was arguing with me on EF said that my log showed 'unknown entity' causing a crash
![image](https://github.com/Reascer/WeaponsOfMinecraft-1.18.2/assets/147657979/97fc2ee2-dce5-4cfd-93aa-bc6e8037f81f)

**Comment by Reascer** [comment]
have you seen this 
![image](https://github.com/Reascer/WeaponsOfMinecraft-1.18.2/assets/48482533/7d56dadc-9cee-48f3-9191-3fe48522031d)

**Comment by Mnibr** [comment]
> have you seen this ![image](https://user-images.githubusercontent.com/48482533/280739646-7d56dadc-9cee-48f3-9191-3fe48522031d.png)

But the trigger rate of this problem in the server is 100%, and using any epic fighting weapon in the server will produce this effect immediately.

**Comment by Mnibr** [comment]
Sorry, I can provide very little information, but I can only tell you that this problem occurred after epic fight 20.5.16, which is not compatible with any version of wom (on the server).

**Comment by Mnibr** [comment]
And 20.5.15 can only be compatible with wom below 20.1.7.26, so please check the code between this time.

**Comment by Reascer** [comment]
you have to restart both your minecarft and the server cuz this bug can occure in both your server and your client

**Comment by Mnibr** [comment]
At present, it can only be determined that particles are causing this problem, as I can see a momentary move before the particles appear, and datapack's weapon did not crash because it did not have particle effects

**Comment by Reascer** [comment]
Ok listen, what you have to do is restart your client first and see if it still do the same bug in your server. if it does do the same bug, restart your server. this is the only way to fix it for now.

**Comment by Cubulous** [comment]
Hi, adding Torment to inventory is also producing this crash issue on servers. Thank you!

**Comment by Mnibr** [comment]
hit mother fucking, this devil can even cause the client to disconnect when sneaking, jumping and landing. I have nothing to say
