### ISSUE TITLE
Teleportation Issue still not fixed.

### ISSUE THREAD

**Issue by Amory42** [Reascer/WeaponsOfMinecraft-1.18.2#49]
Previous issue report:
Whenever I use any of the skills or weapons that involve Teleportation (i.e. Ender Obscuris, Moonlight, Satsujin, etc), then the server disconnects me and gives me this error code

"java.lang.IndexOutOfBoundsException: readerIndex(13) + length(4) exceeds writerIndex(14): PooledUnsafeDirectByteBuf(ridx: 13, widx: 14, cap: 14)"

This has _NOT_ been resolved, it isn't a crash so there is no crash log. 
The mod worked perfectly fine with Essential Multiplayer, but not with servers.

**Comment by Reascer** [comment]
i close issue when i'm aware of it and i i'm doing all what's possible to fix it. that dosen't mean i fixed them some are just not in my area of action. Skill's are loaded in Epic fight not Weapons of minecraft and the issue you are reporting is from skill loading. plz don't spam issue report if i close one it's for a reason.
