### ISSUE TITLE
WOM doesnt work with DawnCraft

### ISSUE THREAD

**Issue by JDerpA** [Reascer/WeaponsOfMinecraft-1.18.2#5]
I added WOM to my mods list and when loading the game it just says it didnt load properly

**Comment by Reascer** [comment]
you need forge 40.2.10 and epicfight latest version

**Comment by JDerpA** [comment]
https://gyazo.com/50dbcd84168c158725a6edff7cffb918

this is what happens when you remove epic fight in place of the newest release on Dawncraft

**Comment by fzrdwa123456** [comment]
> https://gyazo.com/50dbcd84168c158725a6edff7cffb918
> 
> this is what happens when you remove epic fight in place of the newest release on Dawncraft

It's not a WOM problem it's a dawncraft problem because dawncraft has a lot of linkage with the old Epic Fight itself and dawncraft hasn't followed up on the latest version of Epic Fight
