### ISSUE TITLE
Getting kicked from server using Antithesis and Vengeful parry

### ISSUE THREAD

**Issue by HoodBlah** [Reascer/WeaponsOfMinecraft-1.18.2#50]
When I hold the Antithesis or use vengeful parry I get kicked off my server with internal exception error.
![image](https://github.com/Reascer/WeaponsOfMinecraft-1.18.2/assets/89415523/594c638c-9282-4a34-8b8b-4f4d83f0b8ef)
 Will post logs from server and client shortly.

**Comment by HoodBlah** [comment]
[debug.log](https://github.com/Reascer/WeaponsOfMinecraft-1.18.2/files/13276228/debug.log)
[latest.log](https://github.com/Reascer/WeaponsOfMinecraft-1.18.2/files/13276229/latest.log)

**Comment by HoodBlah** [comment]
Server
[debug.log](https://github.com/Reascer/WeaponsOfMinecraft-1.18.2/files/13276237/debug.log)
[latest.log](https://github.com/Reascer/WeaponsOfMinecraft-1.18.2/files/13276238/latest.log)

**Comment by Reascer** [comment]
Restart your server and your Client

**Comment by HoodBlah** [comment]
That does not fix the issue…

**Comment by Reascer** [comment]
repeat the process thrust btw thank you so much for sending both client and server log T-T
