### ISSUE TITLE
Sometimes, there is a problem with Satsujin in 1.20.1

### ISSUE THREAD

**Issue by StarBolt645** [Reascer/WeaponsOfMinecraft-1.18.2#57]
Sometimes, whenever I' am using Satsujin for too long, I' am not able to see the sheathing animation, nor the sheathing sounds anymore, but sometimes I tried to fic this by pressing R button to switch between combat and mining mode, but right now it doesn't work.

**Comment by Reascer** [comment]
Epicfight version :
Weapons of miracles version :
Datapack : yes or no
