### ISSUE TITLE
View map appears wrong

### ISSUE THREAD

**Issue by fzrdwa123456** [Reascer/WeaponsOfMinecraft-1.18.2#6]
This is Epic Fight's original normal map display

https://github.com/Reascer/WeaponsOfMinecraft-1.18.2/assets/130232431/bf3b00be-7249-4794-bdde-679db206b40c

But this is what happened when I added your mod

https://github.com/Reascer/WeaponsOfMinecraft-1.18.2/assets/130232431/d1379dd8-c25c-435c-a0fc-f7c2bb445c5f

**Comment by fzrdwa123456** [comment]
Minecraft 1.18.2
Forge 40.2.10
Epic Fight 18.5.12 release
Weapons Of Miracles 1.7.9

**Comment by Reascer** [comment]
thanks i fixed it ^^
