### ISSUE TITLE
1.20.1: Rendering overlay java.lang.NoSuchFieldError: UPDATE_LIVING_MOTION

### ISSUE THREAD

**Issue by GoldenResolve** [Reascer/WeaponsOfMinecraft-1.18.2#62]
[crash-2023-11-27_14.56.08-client.txt](https://github.com/Reascer/WeaponsOfMinecraft-1.18.2/files/13481629/crash-2023-11-27_14.56.08-client.txt)

Tested with both Forge loaders 47.2.6 and 47.2.8
Latest WOM version 20.1.7.35
Epic Fight: 20.6.1
Forge server fails to start in the command prompt as well

**Comment by Reascer** [comment]
there is something wrong in your set up

**Comment by Reascer** [comment]
i just tested it 
and it worked fine check carefullly mods version are all the same across server and client

**Comment by GoldenResolve** [comment]
> i just tested it and it worked fine check carefullly mods version are all the same across server and client

looks like I have the wrong version of epic fight installed despite updating it, i'll give it another try and see if it works

**Comment by GoldenResolve** [comment]
> > i just tested it and it worked fine check carefullly mods version are all the same across server and client
> 
> looks like I have the wrong version of epic fight installed despite updating it, i'll give it another try and see if it works

everything loaded properly this time but the "outofbounds" bug is still present when I attack with the antitheus weapon
