### ISSUE TITLE
text issue 1.20.1 

### ISSUE THREAD

**Issue by Ghostcody** [Reascer/WeaponsOfMinecraft-1.18.2#63]
Epicfight version : EpicFight-20.5.17.jar
Weapons of miracles version :20.1.7.35
Datapack : no
Crashlog : None

*When/how did it happen : updating to WeaponsOfMiracles-20.1.7.35.jar, seems to have an issue with the options file as it resets it after reverting back to WeaponsOfMiracles-20.1.7.34.jar seems to work fine. I am using a heavily modded modpack which admittedly isn't ideal for testing though 34 works near flawlessly and 35 has this very repeatable issue. 
Log and screenshot below.

[latest.log](https://github.com/Reascer/WeaponsOfMinecraft-1.18.2/files/13494242/latest.log)
![javaw_5YfFNQmVn7](https://github.com/Reascer/WeaponsOfMinecraft-1.18.2/assets/119635545/624f6cb6-9fac-4aab-9fc2-93939f88bfc8)

**Comment by Ghostcody** [comment]
should also note I tried forge version 47.2.5 to 47.2.8

**Comment by Reascer** [comment]
how many mods do you have ?

**Comment by Ghostcody** [comment]
I haven't updated to 20.6.1 as its flagged as beta and it notes it causes unknown crashes. Is it the recommended version?

**Comment by Reascer** [comment]
this is the version i used to build WoM so naturally if you don't use that version you will have wierd stuff

**Comment by Ghostcody** [comment]
No problem I'll try with the latest version when I next update the server. 
Thank you.
