### ISSUE TITLE
when i use weapons of miracles mods weapon to attack then server kick me

### ISSUE THREAD

**Issue by BruleeOrca** [Reascer/WeaponsOfMinecraft-1.18.2#68]
Minecraft version : 1.20.1
Epicfight version : 20.6.2
Weapons of miracles version : 20.17.35
Datapack : no
Crashlog : no

*Latest.log : https://mclo.gs/kLo6j6k

*When/how did it happen : when i use weapons of miracles mods weapon to attack then server kick me ( use epic fight mod )
![image](https://github.com/Reascer/WeaponsOfMinecraft-1.18.2/assets/75370956/edb1e1be-f5c6-47ca-b1a9-c4d877c2b314)
mod list : 
![image](https://github.com/Reascer/WeaponsOfMinecraft-1.18.2/assets/75370956/2697bb86-8475-4c38-a767-767c892a6df2)
![image](https://github.com/Reascer/WeaponsOfMinecraft-1.18.2/assets/75370956/547e2a49-6b72-4951-b8e9-72c19d13389a)
![image](https://github.com/Reascer/WeaponsOfMinecraft-1.18.2/assets/75370956/bc558cd5-bea5-40a6-a8dc-ab94d4f0dd10)
![image](https://github.com/Reascer/WeaponsOfMinecraft-1.18.2/assets/75370956/3ce34241-1f71-4123-9316-fd694fc05ca3)

**Comment by Reascer** [comment]
yup this is thanos bug i've been trying to fix it for month now

**Comment by BruleeOrca** [comment]
What is thanos bug

**Comment by MoonlitJolteon** [comment]
It is the name given to the bug where some players get kicked from the server when they use a weapon from this mod. It's apparently been rather tricky to fix. In a server I run we had everyone install SpitItOut. It's a clientside mod that improves logging for error related server kicks, and for some reason, in our pack at least, 'fixes' the bug. If it doesn't fix it, it will hopefully at least give some better logging to work towards fixing it
[Curseforge Link](https://www.curseforge.com/minecraft/mc-mods/spit-it-out) | [Modrinth Link](https://modrinth.com/mod/spit-it-out)

**Comment by BruleeOrca** [comment]
> 這是一個錯誤的名稱，當一些玩家使用此模組中的武器時，他們會被踢出伺服器。修復起來顯然相當棘手。在我運行的伺服器中，我們讓每個人都安裝 SpitItOut。這是一個客戶端模組，可以改進與伺服器啟動相關的錯誤的日誌記錄，並且出於某種原因，至少在我們的套件中「修復」了錯誤。如果它不能修復它，它至少會提供一些更好的日誌記錄來修復它 [Curseforge Link](https://www.curseforge.com/minecraft/mc-mods/spit-it-out) | [莫德林斯林克](https://modrinth.com/mod/spit-it-out)

it fix the bug
