### ISSUE TITLE
Sastujin does not properly reflect if you're in sheathe stance or not.

### ISSUE THREAD

**Issue by Sazuzaki** [Reascer/WeaponsOfMinecraft-1.18.2#7]
When sheathing your blade, the idle stance does not reflect the user being in sheathed stance. There also seems to be a problem if you spam M1, as I can do the standard auto-attacks while doing iaijutsu.

https://www.youtube.com/watch?v=NvFvxVnDKvs&ab_channel=Sazuzaki

This was done on the latest verion of Forge, Epic Fight, and WoM.

**Comment by Reascer** [comment]
are you in a server

**Comment by Sazuzaki** [comment]
No, all in singleplayer

**Comment by Reascer** [comment]
i tried to reproduce the bug but i don't know why this happen

**Comment by Sazuzaki** [comment]
Hmmm... I'll try with nothing but EF and WoM installed

**Comment by Sazuzaki** [comment]
Weird, guess it's a mod compatibility problem. I'll close both of these issues and do some further testing on my end. Thanks and sorry for the waste of time
