### ISSUE TITLE
Greataxe moveset is missing

### ISSUE THREAD

**Issue by Jetprism** [Reascer/WeaponsOfMinecraft-1.18.2#77]
For some reason greataxe doesn't have any moveset, it nust use 1 handed sword moveset instead. Im playing 1.20.1 rn

**Comment by blessedcarnage** [comment]
May I know which forge version you are using to run the mod, because it is not running for me in most of the forge versions for Minecraft 1.20.1.

**Comment by Jetprism** [comment]
Im using latest version, 47.2.17

**Comment by blessedcarnage** [comment]
I too have been trying to run the mod in the same version but it is not running.😮‍💨
