### ISSUE TITLE
Forge Requirement Not Met for Minecraft 1.20.1!

### ISSUE THREAD

**Issue by blessedcarnage** [Reascer/WeaponsOfMinecraft-1.18.2#78]
The mod **_Weapons of Miracles - Epic Fight v. 20.1.7.35_** always displays error message when the mod is run for every forge version run in Minecraft 1.20.1 from 47.0.0 to 47.2.17. This is a request to please have it checked.
Epic Fight: 20.6.3
WOM: 20.1.7.35
Datapack: No
Crashlog: No

Latest.log: 
[latest.log](https://github.com/Reascer/WeaponsOfMinecraft-1.18.2/files/13657459/latest.log)

Crash Report: 
[crash-2023-12-13_12.55.42-fml.txt](https://github.com/Reascer/WeaponsOfMinecraft-1.18.2/files/13657463/crash-2023-12-13_12.55.42-fml.txt)

When WOM is removed from the mod list the game runs smoothly, but as soon as it is added it simply doesn't let the game run and following message is shown:
![image](https://github.com/Reascer/WeaponsOfMinecraft-1.18.2/assets/66294997/8481f815-0c1f-4e97-81e6-31aa4890da8d)

**Comment by hanzala-903** [comment]
P

**Comment by Ap4uuk** [comment]
+1 I also have a similar error

**Comment by blessedcarnage** [comment]
> +1 I also have a similar error

I did find a temporary fix for it for now, just drop the epic fight mod version to 20.6.2 from the latest 20.6.3

**Comment by blessedcarnage** [comment]
> > +1 I also have a similar error
> 
> I did find a temporary fix for it for now, just drop the epic fight mod version to 20.6.2 from the latest 20.6.3

I think it is because of incompatibility between the WOM and the latest epic fight mod, which I did check for confirmation, and when the epic fight mod version was reduced by one version it worked both standalone as well as with other mods.
