### ISSUE TITLE
stiffComboAttacks gamerule seems to break some weapon movement

### ISSUE THREAD

**Issue by Sazuzaki** [Reascer/WeaponsOfMinecraft-1.18.2#8]
I have the gamerule stiffComboAttacks set to false, and it seems to break some weapon movement functions, particularly Satsujin's counter attack.

https://youtu.be/rzkZHSF4AQk

Think you could just make the WoM arsenal just force the movement, regardless if the gamerule is enabled or not?

**Comment by Reascer** [comment]
I tryed it every thing works fine on my side

**Comment by Sazuzaki** [comment]
Did you set stiffComboAttacks to false? What I'm getting at is I think the weapons should support the gamerule completely or don't support it at all. Being about to move around with the vanilla EF weapons feels great, but it conflicts a little bit with WoM

**Comment by Reascer** [comment]
What i mean by "i tryed it" is i've set the gamerule to false and tryed varius weapon including Satsujin counter attack and on my side every thing worked fine. The problem you are faceing is very specific to your environement and i can't reproduce the bug nor can i find where could it come from. Plus, stiffcomboAttaks is a epicfight gamerule i can't really mess with it.

**Comment by Sazuzaki** [comment]
You were using the Satsujin counter attack while moving right? Actually, try attacking with any weapon from WoM while moving and I think you'll see what I mean on how it conflicts.

You don't have to fix the issue if you don't want to; it's your mod after all. I'm just suggesting you could probably make the WoM arsenal immune to the stiffComboAttacks gamerule, that way people who play with it set to false won't have issues and report them in the future.

**Comment by Reascer** [comment]
i can't make the weapons immune to the stiffComboAttacks gamerule. the reason why you don't get behind the mob is because you are moving therefore the hitbox collide more with the entity hitbox and push you in front of it.

**Comment by Sazuzaki** [comment]
Nah man, don't stress it. It's a super specific issue, and it's not a huge deal if you can't fix it. I'm still having a ton of fun with the mod, so thanks again for your work

**Comment by Reascer** [comment]
well i tryed to fix this in the 1.7.12 but i don't know if it's fixed for you for me it allways dash behind entity ..
