### ISSUE TITLE
Antitheus crash  20.1.7.36.1    12/20/23

### ISSUE THREAD

**Issue by wes10566** [Reascer/WeaponsOfMinecraft-1.18.2#86]
When Antitheus is unequipped, either by dropping the weapon or scrolling to a different slot, the particles remain. If you switch to another weapon either in fight mode or mining mode, the game will instantly crash. This is for the most recent version updated 12/20/23.

https://github.com/Reascer/WeaponsOfMinecraft-1.18.2/assets/154547446/3fd47c0b-e433-4b9a-bcaa-685677b17abc

**Comment by Reascer** [comment]
what version ?!!

**Comment by Reascer** [comment]
send the crashlog and the versions of mods and forge you are using ffs

**Comment by XenoticK** [comment]
Hey, I happened to encounter the same issue with the mod until WOM 20.1.7.36.3 . The new version fixed it, as for all the previous 1.20.1 versions the bug is there. Thx for the update and keep up the good work!
