### ISSUE TITLE
1.20.1 bug

### ISSUE THREAD

**Issue by XiongGaPuo** [Reascer/WeaponsOfMinecraft-1.18.2#87]
Internal Exception: javalangIndex0utofboundsException: readerIndex(13.+ length(4) exceeds uriterIndex(14): PooledunsafeDirectDytebuf(ridx: 13widx: 14 cap:14

**Comment by Reascer** [comment]
![image](https://github.com/Reascer/WeaponsOfMinecraft-1.18.2/assets/48482533/23946cd1-e1bc-4469-98d4-69ffb22b69e4)
