### ISSUE TITLE
1.20.1 serverside crashes

### ISSUE THREAD

**Issue by Ryuco** [Reascer/WeaponsOfMinecraft-1.18.2#88]
Every time i attempt to use the torment, antithesis or staff weaponry from this mod on a server i suddenly crash client side. Singleplayer worlds seem to be fine, and i have had the crash happen with and without extra mods. ill drop my modlist below as well since there might be secondary conflicts.

[Create: Ender Transmission (by Forsteri123)](https://www.curseforge.com/minecraft/mc-mods/create-ender-transmission)
[Iron's Spells' Recipe Additions (by pvz_fan)](https://www.curseforge.com/minecraft/mc-mods/irons-recipe-additions)
[FerriteCore (Forge) (by malte0811)](https://www.curseforge.com/minecraft/mc-mods/ferritecore)
[Nature's Compass (by Chaosyr)](https://www.curseforge.com/minecraft/mc-mods/natures-compass)
[Construction Wand (by ThetaDev)](https://www.curseforge.com/minecraft/mc-mods/construction-wand)
[Better Invisibility (by Purplicious_Cow_)](https://www.curseforge.com/minecraft/mc-mods/better-invisibility)
[Crabber's Delight (by AlabasterLeking)](https://www.curseforge.com/minecraft/mc-mods/crabbers-delight)
[Villager Recruits: Cavalry Update! (by talhanation)](https://www.curseforge.com/minecraft/mc-mods/recruits)
[YUNG's Better Desert Temples (Forge) (by YUNGNICKYOUNG)](https://www.curseforge.com/minecraft/mc-mods/yungs-better-desert-temples)
[YUNG's Better End Island (Forge) (by YUNGNICKYOUNG)](https://www.curseforge.com/minecraft/mc-mods/yungs-better-end-island)
[Alex's Mobs (by sbom_xela)](https://www.curseforge.com/minecraft/mc-mods/alexs-mobs)
[Epic Fight - Impactful (by namelesslk)](https://www.curseforge.com/minecraft/mc-mods/epic-fight-impactful)
[Ender Trigon (by nonamecrackers2)](https://www.curseforge.com/minecraft/mc-mods/ender-trigon)
[Nether's Delight (by lumpazl)](https://www.curseforge.com/minecraft/mc-mods/nethers-delight)
[Moonlight Lib (by MehVahdJukaar)](https://www.curseforge.com/minecraft/mc-mods/selene)
[HT's TreeChop (by hammertater)](https://www.curseforge.com/minecraft/mc-mods/treechop)
[Epic Fight (by maninthe_home)](https://www.curseforge.com/minecraft/mc-mods/epic-fight-mod)
[Iron's Spells 'n Spellbooks (by Iron431)](https://www.curseforge.com/minecraft/mc-mods/irons-spells-n-spellbooks)
[Better Archeology (by Pandarix)](https://www.curseforge.com/minecraft/mc-mods/better-archeology)
[Minium Stone [Forge & Fabric] (by Fuzs)](https://www.curseforge.com/minecraft/mc-mods/minium-stone)
[Kotlin for Forge (by thedarkcolour)](https://www.curseforge.com/minecraft/mc-mods/kotlin-for-forge)
[Healing Flasks (by mumihp)](https://www.curseforge.com/minecraft/mc-mods/healing-flasks)
[Random Crits (by InfernalEclipse)](https://www.curseforge.com/minecraft/mc-mods/random-crits)
[Iron's Rpg Tweaks (by Iron431)](https://www.curseforge.com/minecraft/mc-mods/irons-rpg-tweaks)
[Netherific (by lixir)](https://www.curseforge.com/minecraft/mc-mods/netherific)
[YUNG's Better Ocean Monuments (Forge) (by YUNGNICKYOUNG)](https://www.curseforge.com/minecraft/mc-mods/yungs-better-ocean-monuments)
[Not Enough Crashes (Forge) (by NatanFudge)](https://www.curseforge.com/minecraft/mc-mods/not-enough-crashes-forge)
[Architectury API (Fabric/Forge/NeoForge) (by shedaniel)](https://www.curseforge.com/minecraft/mc-mods/architectury-api)
[Camps. Castles. Carriages. (by Eugene2000)](https://www.curseforge.com/minecraft/mc-mods/camps-castles-carriages)
[Just Enough Items (JEI) (by mezz)](https://www.curseforge.com/minecraft/mc-mods/jei)
[Sapience (by the_infamous_1)](https://www.curseforge.com/minecraft/mc-mods/sapience)
[Sophisticated Core (by P3pp3rF1y)](https://www.curseforge.com/minecraft/mc-mods/sophisticated-core)
[SuperMartijn642's Config Lib (by SuperMartijn642)](https://www.curseforge.com/minecraft/mc-mods/supermartijn642s-config-lib)
[NoCube's Villagers Sell Animals (by nocubeyt)](https://www.curseforge.com/minecraft/mc-mods/villagers-sell-animals)
[GeckoLib (by Gecko)](https://www.curseforge.com/minecraft/mc-mods/geckolib)
[Drink Beer Refill (by DragonsPlus)](https://www.curseforge.com/minecraft/mc-mods/drink-beer-refill)
[Ocean's Delight (by scouter567)](https://www.curseforge.com/minecraft/mc-mods/oceans-delight)
[Antique Atlas Reborn (by kallmetony)](https://www.curseforge.com/minecraft/mc-mods/antique-atlas-reborn)
[Mouse Tweaks (by YaLTeR)](https://www.curseforge.com/minecraft/mc-mods/mouse-tweaks)
[Mutant Monsters [Forge & Fabric] (by Fuzs)](https://www.curseforge.com/minecraft/mc-mods/mutant-monsters)
[Relics (by SSKirillSS)](https://www.curseforge.com/minecraft/mc-mods/relics-mod)
[Create (by simibubi)](https://www.curseforge.com/minecraft/mc-mods/create)
[playerAnimator (by KosmX)](https://www.curseforge.com/minecraft/mc-mods/playeranimator)
[Cosmetic Armor Reworked (by LainMI)](https://www.curseforge.com/minecraft/mc-mods/cosmetic-armor-reworked)
[YUNG's Better Mineshafts (Forge) (by YUNGNICKYOUNG)](https://www.curseforge.com/minecraft/mc-mods/yungs-better-mineshafts-forge)
[Create Crafts & Additions (by MRHminer)](https://www.curseforge.com/minecraft/mc-mods/createaddition)
[Sky Villages [Forge] (by y4z0n)](https://www.curseforge.com/minecraft/mc-mods/sky-villages-forge)
[mutil (by mickelus)](https://www.curseforge.com/minecraft/mc-mods/mutil)
[Cristel Lib (by Cristelknight)](https://www.curseforge.com/minecraft/mc-mods/cristel-lib)
[Create Encased (by iglee42)](https://www.curseforge.com/minecraft/mc-mods/create-encased)
[YUNG's Better Nether Fortresses (Forge) (by YUNGNICKYOUNG)](https://www.curseforge.com/minecraft/mc-mods/yungs-better-nether-fortresses)
[Curios API (Forge/NeoForge) (by TheIllusiveC4)](https://www.curseforge.com/minecraft/mc-mods/curios)
[Puzzles Lib [Forge & Fabric] (by Fuzs)](https://www.curseforge.com/minecraft/mc-mods/puzzles-lib)
[Serene Seasons (by TheAdubbz)](https://www.curseforge.com/minecraft/mc-mods/serene-seasons)
[Relics: Alex's Mobs Compat (by SSKirillSS)](https://www.curseforge.com/minecraft/mc-mods/ram-compat)
[AppleSkin (by squeek502)](https://www.curseforge.com/minecraft/mc-mods/appleskin)
[ModernFix (by embeddedt)](https://www.curseforge.com/minecraft/mc-mods/modernfix)
[ChoiceTheorem's Overhauled Village (by ChoiceTheorem)](https://www.curseforge.com/minecraft/mc-mods/choicetheorems-overhauled-village)
[Create : Misc & Things (by to0pa_fr)](https://www.curseforge.com/minecraft/mc-mods/create-misc-and-things)
[Balm (Forge Edition) (by BlayTheNinth)](https://www.curseforge.com/minecraft/mc-mods/balm)
[OctoLib (by SSKirillSS)](https://www.curseforge.com/minecraft/mc-mods/octo-lib)
[Towns and Towers (by Biban_Auriu)](https://www.curseforge.com/minecraft/mc-mods/towns-and-towers)
[Enchanting Infuser [Forge & Fabric] (by Fuzs)](https://www.curseforge.com/minecraft/mc-mods/enchanting-infuser-forge)
[Let's Forge Bronze And Iron (by szczypikrul)](https://www.curseforge.com/minecraft/mc-mods/lets-forge-bronze-and-iron)
[Tarot Cards (by shiroroku)](https://www.curseforge.com/minecraft/mc-mods/tarot-cards)
[L_Ender 's Cataclysm (by mcl_ender)](https://www.curseforge.com/minecraft/mc-mods/l_ender-s-cataclysm)
[Create: Oppenheimered (by betathunder1)](https://www.curseforge.com/minecraft/mc-mods/create-oppenheimered)
[Amplified Nether (by Starmute)](https://www.curseforge.com/minecraft/mc-mods/amplified-nether)
[Goblin Traders (by MrCrayfish)](https://www.curseforge.com/minecraft/mc-mods/goblin-traders)
[YUNG's Better Jungle Temples (Forge) (by YUNGNICKYOUNG)](https://www.curseforge.com/minecraft/mc-mods/yungs-better-jungle-temples)
[Vintage Delight (by Ribs498)](https://www.curseforge.com/minecraft/mc-mods/vintage-delight)
[MmmMmmMmmMmm (Target Dummy) (by MehVahdJukaar)](https://www.curseforge.com/minecraft/mc-mods/mmmmmmmmmmmm)
[Small Ships [Fabric & Forge] (by talhanation)](https://www.curseforge.com/minecraft/mc-mods/small-ships)
[Cataclysm Delight (by hippo0824)](https://www.curseforge.com/minecraft/mc-mods/cataclysm-delight)
[Create Slice & Dice (by possible_triangle)](https://www.curseforge.com/minecraft/mc-mods/slice-and-dice)
[NetherPortalFix (by BlayTheNinth)](https://www.curseforge.com/minecraft/mc-mods/netherportalfix)
[Controlling (by Jaredlll08)](https://www.curseforge.com/minecraft/mc-mods/controlling)
[Miner's Delight + (by soytutta)](https://www.curseforge.com/minecraft/mc-mods/miners-delight-plus)
[Piglin Proliferation (by almightytallestred)](https://www.curseforge.com/minecraft/mc-mods/piglin-proliferation)
[Fast Leaf Decay (by olafskiii)](https://www.curseforge.com/minecraft/mc-mods/fast-leaf-decay)
[YUNG's API (Forge) (by YUNGNICKYOUNG)](https://www.curseforge.com/minecraft/mc-mods/yungs-api)
[Cloth Config API (Fabric/Forge/NeoForge) (by shedaniel)](https://www.curseforge.com/minecraft/mc-mods/cloth-config)
[Alex's Caves (by sbom_xela)](https://www.curseforge.com/minecraft/mc-mods/alexs-caves)
[Citadel (by sbom_xela)](https://www.curseforge.com/minecraft/mc-mods/citadel)
[Patchouli (by Vazkii)](https://www.curseforge.com/minecraft/mc-mods/patchouli)
[Mutants Buff (by angrymutantendermanz)](https://www.curseforge.com/minecraft/mc-mods/mutants-buff)
[Bosses of Mass Destruction [FORGE] (by CerbonXD)](https://www.curseforge.com/minecraft/mc-mods/bosses-of-mass-destruction-forge)
[Framework (by MrCrayfish)](https://www.curseforge.com/minecraft/mc-mods/framework)
[Sophisticated Backpacks (by P3pp3rF1y)](https://www.curseforge.com/minecraft/mc-mods/sophisticated-backpacks)
[Little Geode (by transpirateur)](https://www.curseforge.com/minecraft/mc-mods/little-geode)
[Biomes O' Plenty (by Forstride)](https://www.curseforge.com/minecraft/mc-mods/biomes-o-plenty)
[Connectivity[Forge/Fabric] (by someaddon)](https://www.curseforge.com/minecraft/mc-mods/connectivity)
[Villager Workers: Traveling Merchant Update! (by talhanation)](https://www.curseforge.com/minecraft/mc-mods/workers)
[YUNG's Better Dungeons (Forge) (by YUNGNICKYOUNG)](https://www.curseforge.com/minecraft/mc-mods/yungs-better-dungeons)
[Ore Growth (by SuperMartijn642)](https://www.curseforge.com/minecraft/mc-mods/ore-growth)
[Wandering Bags (by Furti_Two)](https://www.curseforge.com/minecraft/mc-mods/wandering-bags)
[Heartstone (by plantspookable)](https://www.curseforge.com/minecraft/mc-mods/heartstone)
[Waystones (by BlayTheNinth)](https://www.curseforge.com/minecraft/mc-mods/waystones)
[Arcane Lanterns [Forge & Fabric] (by Fuzs)](https://www.curseforge.com/minecraft/mc-mods/arcane-lanterns)
[Soul fire'd (by CrystalSpider)](https://www.curseforge.com/minecraft/mc-mods/soul-fired)
[Caelus API (Forge/NeoForge) (by TheIllusiveC4)](https://www.curseforge.com/minecraft/mc-mods/caelus)
[Magnesium/Rubidium Dynamic Lights (by Anthxny)](https://www.curseforge.com/minecraft/mc-mods/dynamiclights-reforged)
[Weapons of Miracles - epic fight (by reascer)](https://www.curseforge.com/minecraft/mc-mods/weapons-of-miracles-epicfight)
[Fastload (by StockiesLad)](https://www.curseforge.com/minecraft/mc-mods/fastload)
[Rats (by sbom_xela)](https://www.curseforge.com/minecraft/mc-mods/rats)
[Iron Chests (by ProgWML6)](https://www.curseforge.com/minecraft/mc-mods/iron-chests)
[Lootr (Forge) (by Noobanidus)](https://www.curseforge.com/minecraft/mc-mods/lootr)
[Create : Armory (by Chilllliii)](https://www.curseforge.com/minecraft/mc-mods/create-armory)
[SuperMartijn642's Core Lib (by SuperMartijn642)](https://www.curseforge.com/minecraft/mc-mods/supermartijn642s-core-lib)
[Rings of Ascension (Forge) (by focamacho)](https://www.curseforge.com/minecraft/mc-mods/rings-of-ascension)
[Realm RPG: Fallen Adventurers (by nocubeyt)](https://www.curseforge.com/minecraft/mc-mods/realm-rpg-fallen-adventurers)
[Pehkui (by Virtuoel)](https://www.curseforge.com/minecraft/mc-mods/pehkui)
[Farmer's Delight (by vectorwing)](https://www.curseforge.com/minecraft/mc-mods/farmers-delight)
[TerraBlender (Forge) (by TheAdubbz)](https://www.curseforge.com/minecraft/mc-mods/terrablender)
[Clumps (by Jaredlll08)](https://www.curseforge.com/minecraft/mc-mods/clumps)
[Immersive Armors [Fabric/Forge] (by Conczin)](https://www.curseforge.com/minecraft/mc-mods/immersive-armors)
[Cupboard (by someaddon)](https://www.curseforge.com/minecraft/mc-mods/cupboard)
[Villages&Pillages (by Faboslav)](https://www.curseforge.com/minecraft/mc-mods/villages-and-pillages)
[Immersive Aircraft [Fabric/Forge] (by Conczin)](https://www.curseforge.com/minecraft/mc-mods/immersive-aircraft)
[Create Coins (by Bluejamathons)](https://www.curseforge.com/minecraft/mc-mods/create-coins)
[Searchables (by Jaredlll08)](https://www.curseforge.com/minecraft/mc-mods/searchables)
[Lucky's Spelunker's Charm II (by LuckyOwl)](https://www.curseforge.com/minecraft/mc-mods/spelunkers-charm-ii)
[End's Delight (by foggyhillside)](https://www.curseforge.com/minecraft/mc-mods/ends-delight)

**Comment by Ryuco** [comment]
also crashed when swinging the Herrscher

**Comment by Texbio** [comment]
{
  "f_132075_": "translation{key='disconnect.genericReason', args=[Internal Exception: java.lang.IndexOutOfBoundsException: readerIndex(13) + length(4) exceeds writerIndex(14): UnpooledByteBufAllocator$InstrumentedUnpooledUnsafeHeapByteBuf(ridx: 13, widx: 14, cap: 14)]}"
}
I am getting this crash on a server when holding wom:tormented_mind, on v20.1.7.36.2 for 1.20.1, using epic fight 20.6.3

**Comment by Reascer** [comment]
![image](https://github.com/Reascer/WeaponsOfMinecraft-1.18.2/assets/48482533/00370203-0ae2-45bf-9068-d29c0230b26f)
