### ISSUE TITLE
Particle effects show abnormal and twisted joints in action

### ISSUE THREAD

**Issue by fzrdwa123456** [Reascer/WeaponsOfMinecraft-1.18.2#9]
https://github.com/Reascer/WeaponsOfMinecraft-1.18.2/assets/130232431/40ce79d0-da1b-43dd-be03-bf54ee7cf734

As the title says, the particle effects appear black and purple instead of the normal particle textures and there are some unusual distortions in the actions of the weapons. Can you fix them?

**Comment by fzrdwa123456** [comment]
Minecraft 1.18.2
Forge 40.2.10
Epic Fight 18.5.12 release
Weapons Of Miracles 1.7.11

**Comment by fzrdwa123456** [comment]
If only you could fix the abnormal joint distortion of the character weapon. Thank you for the pleasure your mod brought me

**Comment by fzrdwa123456** [comment]
Most of the weapons in your mod have characters with abnormally twisted arm joints

**Comment by Reascer** [comment]
try again in a normal world i'll try to fix this

**Comment by fzrdwa123456** [comment]
> try again in a normal world i'll try to fix this

Particle effects have been fixed in the latest version Of Weapons Of Miracles 1.7.12, but there are still some particle effects that show problems that are not your fault but Epic's Fight the problem of concrete problems can go to https://github.com/Yesssssman/epicfightmod/issues/1382 here

**Comment by fzrdwa123456** [comment]
https://github.com/Reascer/WeaponsOfMinecraft-1.18.2/assets/130232431/e232c890-8085-40f5-baf4-5dedcb8d4493

It can be seen that the player's arm joints are abnormally twisted
Weapons Of Miracles-1.7.12

**Comment by fzrdwa123456** [comment]
> 在正常世界中重试，我会尝试解决此问题

Weapons Of Miracles-1.7.12

**Comment by fzrdwa123456** [comment]
> try again in a normal world i'll try to fix this

![Screenshot 2023-10-05 130407](https://github.com/Reascer/WeaponsOfMinecraft-1.18.2/assets/130232431/1560413c-fece-4db5-a211-5073f282e515)

**Comment by Reascer** [comment]
Yeah this is intended
