### ISSUE TITLE
Torment special ability meter doesn't funcion.

### ISSUE THREAD

**Issue by Mordunce** [Reascer/WeaponsOfMinecraft-1.18.2#92]
Torment works just fine, but the ability meter keeps flickering between the percentage of the number and 0 making it quite difficult to know how close you are to getting the ability.  You can still use the ability and there are no bugs with that, just the meter. I will also mention that this only happens in survival. 

Short version: Torment meter no work pls fix

**Comment by Briknex** [comment]
It's intentional, the ability makes the skill gauge unreadable.
