### ISSUE TITLE
The mods itself does not run.

### ISSUE THREAD

**Issue by Rosenkreuzer** [Reascer/WeaponsOfMinecraft-1.18.2#94]
![스크린샷 2024-01-04 154037](https://github.com/Reascer/WeaponsOfMinecraft-1.18.2/assets/154269080/be75b84c-0e98-46e2-9462-8e38bfd9c45a)

Forge Ver: 47.2.17
Epic Fight ver: 20.6.3
Weapons Of Miracles ver: 20.1.7.35

The mod itself does not run. Even if you try to run it after placing all other mods in a separate folder, it will not run.

**Comment by Reascer** [comment]
downloads latest Weapons of miracles thank you
