### ISSUE TITLE
Entities error

### ISSUE THREAD

**Issue by Fascaroo** [Reascer/WeaponsOfMinecraft-1.18.2#95]
![2024-01-06_17 21 13](https://github.com/Reascer/WeaponsOfMinecraft-1.18.2/assets/155829066/13c561b8-45f4-4060-8d5d-304eb8c7b790)

Forge Ver: 47.2.0
Epic Fight ver: 20.5.17
Weapons Of Miracles ver: 18.1.7.36.3

**Comment by Reascer** [comment]
update forge
