### ISSUE TITLE
Question/Issue with Configuration

### ISSUE THREAD

**Issue by Mikaaah** [Reascer/WeaponsOfMinecraft-1.18.2#99]
The config file is empty, and it seems there is no file in the data folder to alter the droprates of the weapons/disable them entirely. Is there a way to disable them from spawning in chests?

**Comment by Reascer** [comment]
i think there is a mod that does that

**Comment by Mikaaah** [comment]
Do you by any chance know which one? Thanks in advance

**Comment by Reascer** [comment]
nop
